trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - README.md

stages:
- stage: Acceptance
  variables:
   AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
   AZURE_ENV_NAME: acc
   AZURE_LOCATION: $(AZURE_LOCATION)
  jobs:
  - deployment: 'Acceptance'
    environment: acc
    pool:
     vmImage: ubuntu-latest
    strategy:
        runOnce:
         deploy:
          steps:
          - checkout: self
          - template: azdcli.yml
            parameters:
             serviceConnection: azconnection

- stage: Production
  variables:
   AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
   AZURE_ENV_NAME: prd
   AZURE_LOCATION: $(AZURE_LOCATION)
  jobs:
  - deployment: 'Production'
    environment: prd
    pool:
     vmImage: ubuntu-latest
    strategy:
        runOnce:
          deploy:
           steps:
           - checkout: self
           - template: azdcli.yml
             parameters:
              serviceConnection: azconnection