parameters:
- name: serviceConnection          
  type: string
- name: app          
  type: string

steps:
- task: Bash@3
  displayName: Install azd
  inputs:
    targetType: 'inline'
    script: |
      curl -fsSL https://aka.ms/install-azd.sh | bash
- task: PowerShell@2
  displayName: Configure AZD to Use AZ CLI Authentication.
  inputs:
    targetType: inline
    script: |
      azd config set auth.useAzCliAuth "true"
    pwsh: true
- task: NuGetAuthenticate@1
- task: AzureCLI@2
  displayName: Package ${{ parameters.app }} Application
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptType: bash
    scriptLocation: inlineScript
    keepAzSessionActive: true
    inlineScript: |
      mkdir -p ./dist
      azd package ${{ parameters.app }} --output-path ./dist/${{ parameters.app }}-package.zip  --no-prompt
      echo "✅ Application ${{ parameters.app }} packaged successfully"
- task: PublishPipelineArtifact@1
  displayName: Upload ${{ parameters.app }} Package Artifact
  inputs:
    targetPath: ./dist/${{ parameters.app }}-package.zip
    artifact: ${{ parameters.app }}-package
    publishLocation: 'pipeline'
  